// AUTO-GENERATED by scripts/sync-harness-from-results.mjs — do not edit by hand.
// Source: logomesh-startup/results/real_prs_run_*.json

export const HARNESS_AGGREGATE = {
  batchRunFiles: 510,
  fileRowsTotal: 1979,
  uniquePullRequests: 333,
  distinctRepos: 115,
  confirmedFindingsSum: 480,
  fileRowsWithPrComment: 212,
  source: "logomesh-startup/results/real_prs_run_*.json",
} as const;

export type HarnessShowcaseRow = {
  repo: string;
  prNumber: number;
  title: string;
  fileBasename: string;
  confirmedFindings: number;
};

/** Diverse OSS PRs where the harness surfaced at least one confirmed finding (one row per repo). */
export const HARNESS_SHOWCASE: readonly HarnessShowcaseRow[] = [
  {
    repo: "dj-stripe/dj-stripe",
    prNumber: 2187,
    title: "Fix critical bugs in model definitions",
    fileBasename: "billing.py",
    confirmedFindings: 12,
  },
  {
    repo: "formencode/formencode",
    prNumber: 176,
    title: "Protect `cgi`",
    fileBasename: "validators.py",
    confirmedFindings: 9,
  },
  {
    repo: "seleniumbase/SeleniumBase",
    prNumber: 4295,
    title: "CDP Mode: Patch 100",
    fileBasename: "prepare.py",
    confirmedFindings: 9,
  },
  {
    repo: "auth0/auth0-python",
    prNumber: 799,
    title: "feat:Add `Auth0-Custom-Domain` header support for Multiple Custom Domains (MCD)",
    fileBasename: "management_client.py",
    confirmedFindings: 7,
  },
  {
    repo: "django-oscar/django-oscar",
    prNumber: 4552,
    title: "[FEAT] Add code in product review",
    fileBasename: "abstract_models.py",
    confirmedFindings: 7,
  },
  {
    repo: "pallets/werkzeug",
    prNumber: 3148,
    title: "relax get_host strictness",
    fileBasename: "utils.py",
    confirmedFindings: 7,
  },
  {
    repo: "redis/redis-py",
    prNumber: 4029,
    title: "Reorganize unit tests grouping - extracting the tests that define their hardcoded client configuration separately",
    fileBasename: "tasks.py",
    confirmedFindings: 7,
  },
  {
    repo: "dynaconf/dynaconf",
    prNumber: 1363,
    title: "fix: support Redis URL scheme for TLS connections",
    fileBasename: "redis_loader.py",
    confirmedFindings: 6,
  },
];
